### ISSUE TITLE
use ansible!

### ISSUE THREAD

**Issue by dyindude** [gnosthi/digital-ocean-image-getter#1]
http://docs.ansible.com/ansible/latest/uri_module.html

```
- name: get digital_ocean_images
  uri:
    url: https://api.digitalocean.com/v2/images
    HEADER_Authorization: "Bearer {{ digital_ocean_token }}"
    return_content: yes
  register: digital_ocean_images
```

something like the above would place the json result in `digital_ocean_images.content` which you could then parse/query with jinja `json` filters http://docs.ansible.com/ansible/latest/playbooks_filters.html
